# Generated by Django 4.2.30 on 2026-06-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_vetting', '0007_cosmicflows4q3c_hecate1q3c_hecate2q3c_lsdr10southq3c_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGalaxyQ3C',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objname', models.TextField(blank=True, null=True)),
                ('ra', models.FloatField(blank=True, null=True)),
                ('dec', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('z_err', models.FloatField(blank=True, null=True)),
                ('z_pos_err', models.FloatField(blank=True, null=True)),
                ('z_neg_err', models.FloatField(blank=True, null=True)),
                ('z_type', models.TextField(blank=True, null=True)),
                ('lumdist', models.FloatField(blank=True, null=True)),
                ('lumdist_err', models.FloatField(blank=True, null=True)),
                ('lumdist_pos_err', models.FloatField(blank=True, null=True)),
                ('lumdist_neg_err', models.FloatField(blank=True, null=True)),
                ('default_mag', models.FloatField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('submitter', models.TextField(blank=True, null=True)),
                ('og_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usergalaxy_q3c',
                'managed': True,
            },
        ),
    ]
