# Generated by Django 4.2.23 on 2026-06-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_vetting', '0008_usergalaxyq3c'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvccQ3C',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('evcc', models.IntegerField()),
                ('vcc', models.CharField(blank=True, max_length=4, null=True)),
                ('ngc', models.CharField(blank=True, max_length=5, null=True)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('fra', models.FloatField(blank=True, null=True)),
                ('fdec', models.FloatField(blank=True, null=True)),
                ('fiber_offset', models.FloatField(blank=True, null=True)),
                ('srvel', models.FloatField(blank=True, null=True)),
                ('nrvel', models.FloatField(blank=True, null=True)),
                ('mem_infall', models.CharField(blank=True, max_length=1, null=True)),
                ('mem_vcc', models.CharField(blank=True, max_length=1, null=True)),
                ('pmorph', models.CharField(blank=True, max_length=8, null=True)),
                ('smorph', models.CharField(blank=True, max_length=2, null=True)),
                ('nmorph', models.IntegerField(blank=True, null=True)),
                ('vmorph', models.CharField(blank=True, max_length=19, null=True)),
                ('umag', models.FloatField(blank=True, null=True)),
                ('e_umag', models.FloatField(blank=True, null=True)),
                ('gmag', models.FloatField(blank=True, null=True)),
                ('e_gmag', models.FloatField(blank=True, null=True)),
                ('rmag', models.FloatField(blank=True, null=True)),
                ('e_rmag', models.FloatField(blank=True, null=True)),
                ('imag', models.FloatField(blank=True, null=True)),
                ('e_imag', models.FloatField(blank=True, null=True)),
                ('zmag', models.FloatField(blank=True, null=True)),
                ('e_zmag', models.FloatField(blank=True, null=True)),
                ('rad', models.FloatField(blank=True, null=True)),
                ('r50', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evcc_q3c',
                'managed': False,
            },
        ),
    ]
